In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size=1000

In [5]:
one_hot_represent=[one_hot(words,voc_size)for words in sent]

In [6]:
one_hot_represent

[[299, 851, 208, 451],
 [299, 851, 208, 612],
 [299, 340, 208, 709],
 [202, 890, 41, 472, 650],
 [202, 890, 41, 472, 533],
 [606, 299, 687, 208, 750],
 [108, 701, 811, 472]]

In [7]:
from tensorflow.keras.layers import Embedding,Input
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_represent,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 299 851 208 451]
 [  0   0   0   0 299 851 208 612]
 [  0   0   0   0 299 340 208 709]
 [  0   0   0 202 890  41 472 650]
 [  0   0   0 202 890  41 472 533]
 [  0   0   0 606 299 687 208 750]
 [  0   0   0   0 108 701 811 472]]


In [10]:
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

d:\Udemy_ML_and_DL\Project1_ANN\venv\lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 369ms/step


array([[[ 2.51087807e-02,  1.37969963e-02,  1.62773989e-02,
          1.64815895e-02,  1.62732042e-02,  4.73752655e-02,
         -4.48393933e-02,  7.23141432e-03,  4.40307148e-02,
         -6.50114939e-03],
        [ 2.51087807e-02,  1.37969963e-02,  1.62773989e-02,
          1.64815895e-02,  1.62732042e-02,  4.73752655e-02,
         -4.48393933e-02,  7.23141432e-03,  4.40307148e-02,
         -6.50114939e-03],
        [ 2.51087807e-02,  1.37969963e-02,  1.62773989e-02,
          1.64815895e-02,  1.62732042e-02,  4.73752655e-02,
         -4.48393933e-02,  7.23141432e-03,  4.40307148e-02,
         -6.50114939e-03],
        [ 2.51087807e-02,  1.37969963e-02,  1.62773989e-02,
          1.64815895e-02,  1.62732042e-02,  4.73752655e-02,
         -4.48393933e-02,  7.23141432e-03,  4.40307148e-02,
         -6.50114939e-03],
        [-1.06824040e-02,  2.64033787e-02,  2.81115435e-02,
         -4.84490655e-02,  4.71073389e-03, -3.21977511e-02,
         -2.06983220e-02,  2.51455046e-02,  2.745587

In [14]:
embedded_docs[0]

array([  0,   0,   0,   0, 299, 851, 208, 451], dtype=int32)

In [17]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step


array([[[ 2.51087807e-02,  1.37969963e-02,  1.62773989e-02,
          1.64815895e-02,  1.62732042e-02,  4.73752655e-02,
         -4.48393933e-02,  7.23141432e-03,  4.40307148e-02,
         -6.50114939e-03],
        [ 2.51087807e-02,  1.37969963e-02,  1.62773989e-02,
          1.64815895e-02,  1.62732042e-02,  4.73752655e-02,
         -4.48393933e-02,  7.23141432e-03,  4.40307148e-02,
         -6.50114939e-03],
        [ 2.51087807e-02,  1.37969963e-02,  1.62773989e-02,
          1.64815895e-02,  1.62732042e-02,  4.73752655e-02,
         -4.48393933e-02,  7.23141432e-03,  4.40307148e-02,
         -6.50114939e-03],
        [ 2.51087807e-02,  1.37969963e-02,  1.62773989e-02,
          1.64815895e-02,  1.62732042e-02,  4.73752655e-02,
         -4.48393933e-02,  7.23141432e-03,  4.40307148e-02,
         -6.50114939e-03],
        [-1.06824040e-02,  2.64033787e-02,  2.81115435e-02,
         -4.84490655e-02,  4.71073389e-03, -3.21977511e-02,
         -2.06983220e-02,  2.51455046e-02,  2.745587